type: object
properties:
  configId:
    type: integer
    example: 1
  key:
    type: string
    example: "version"
  value:
    type: string
    example: "0.5.0"
  description:
    type: string
    example: "系统版本号"
  createdAt:
    type: string
    example: "2017-08-19T17:08:09.000Z"
  updatedAt:
    type: string
    example: "2017-08-19T17:08:09.000Z"
